server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/happraisal
    username: happraisameAdimin
    password: happraisale_password
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    database-platform: org.postgresql.dialect.PostgreSQLDialect
    properties:
        hibernate:
            format_sql: true
            hbm2ddl:
              auto: create
