# Use postgres/example user/password credentials
version: '3.1'

services:


  db:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: happraisal_dbpassword!
      POSTGRES_USER: happraisal_dbuser
      POSTGRES_DB: happraisal_dbname
    healthcheck:
      test: ["CMD-SHELL",  "pg_isready -d happraisaldb -U happraisal || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    expose:
      - 5432

  liquibase:
    image:  liquibase/liquibase:4.25
    depends_on:
       db:
        condition: service_healthy
    environment:
        LIQUIBASE_COMMAND_USERNAME: happraisal_dbuser
        LIQUIBASE_COMMAND_PASSWORD: happraisal_dbpassword!
        LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/happraisal_dbnamedb
        LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
        LIQUIBASE_COMMAND_CHANGELOG_FILE: happraisal.changelog.yml
    command: update
    volumes:
      - ../../../liquibase/changelog:/liquibase/changelog

