# Use postgres/example user/password credentials
version: '3.1'

services:


  db:
    image: postgres:14.7-alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: "happraisal_password!"
      POSTGRES_USER: happraisal
      POSTGRES_DB: happraisaldb
    healthcheck:
      test: ["CMD-SHELL",  "pg_isready -d happraisaldb -U happraisal || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    expose:
      - 5432

  liquibase:
    image:  liquibase/liquibase:4.25
    depends_on:
       db:
        condition: service_healthy
    environment:
        LIQUIBASE_COMMAND_USERNAME: happraisal
        LIQUIBASE_COMMAND_PASSWORD: "happraisal_password!"
        LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/happraisaldb
        LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
        LIQUIBASE_COMMAND_CHANGELOG_FILE: happraisal.changelog.yml
    command: update
    volumes:
      - ../../../liquibase/changelog:/liquibase/changelog

