# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: happraisalePassword
      POSTGRES_USER: happraisameAdimin
      POSTGRES_DB: happraisal
    expose:
      - 5432
