# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  push:
    branches:
    - develop
    - ci_*

permissions:
  contents: read

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - run: ./gradlew assemble --no-daemon
 
 
  spotless:
    runs-on: ubuntu-latest
    needs: assemble
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Dependency Check
      run: ./gradlew spotlessCheck

  
  unit-tests:
    runs-on: ubuntu-latest
    needs: spotless
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - run: ./gradlew test --no-daemon
    - name: Archive unit test report
      uses: actions/upload-artifact@v4
      with:
        name: unit-tests-report
        path: |
            build/reports/tests/integrationTest
            build/jacoco/integrationTest.exec
        retention-days: 1
        
  integration-tests:
    runs-on: ubuntu-latest
    needs: spotless
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - run: ./gradlew integrationTest --no-daemon
    - name: Archive integration test report
      uses: actions/upload-artifact@v4
      with:
        name: integration-tests-report
        path: |
            build/reports/tests/integrationTest
            build/jacoco/integrationTest.exec
        retention-days: 1
        
  system-tests:
    runs-on: ubuntu-latest
    needs: spotless
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - run: ./gradlew systemTest --no-daemon
    - name: Archive system test report
      uses: actions/upload-artifact@v4
      with:
        name: system-tests-report
        path: |
            build/reports/tests/systemTest
            build/jacoco/systemTest.exec
        retention-days: 1

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, system-tests]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - run: ./gradlew jacocoTestReport sonar
      env:
        SONAR_ORGANIZATION: ${{vars.SONAR_ORGANIZATION}}
        SONAR_PROJECT_KEY: ${{vars.SONAR_PROJECT_KEY}}
        SONAR_PROJECT_NAME: ${{vars.SONAR_PROJECT_NAME}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}